baseURL = "https://fardog.io/"
languageCode = "en-us"
title = "fardog.io"
copyright = "Nathan Wittstock"
enableRobotsTXT = true

[[menu.main]]
name                   = "Projects"
weight                 = -110
identifier             = "projects"
url                    = "/projects/"

[[menu.main]]
name                   = "Blog"
weight                 = -100
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "Contact"
weight                 = -90
identifier             = "contact"
url                    = "/contact/"

[permalinks]
blog = "blog/:year/:month/:day/:title/"

[params]
latestPostsCount       = 5

dateFormatShort        = "Jan 2, 2006"
dateFormatISO          = "2006-01-02T15:04:05-0700"

faviconPath            = "/favicon.ico"

robotsBlockSourceUrl   = "https://raw.githubusercontent.com/ai-robots-txt/ai.robots.txt/main/robots.txt"

  [params.contentLicense]
  text = "CC BY 4.0"
  url = "https://creativecommons.org/licenses/by/4.0/"

  [params.codeLicense]
  text = "MIT"
  url = "https://github.com/fardog/fardog.io/blob/master/LICENSE"

  [params.repository]
  text = "source"
  url = "https://github.com/fardog/fardog.io/"

[markup]
  [markup.highlight]
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    noClasses = false
