baseURL = "https://fardog.io/"
languageCode = "en-us"
title = "fardog.io"
theme = "cocoa"

[[menu.main]]
name                   = "Projects"
weight                 = -110
identifier             = "projects"
url                    = "/projects/"

[[menu.main]]
name                   = "Blog"
weight                 = -100
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "Contact"
weight                 = -90
identifier             = "contact"
url                    = "/contact/"

[permalinks]
blog = "blog/:year/:month/:day/:title/"

[params]
latestpostscount       = 5
i18n_flags             = false
author                 = "Nathan Wittstock"
cachebuster            = false
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
faviconfile            = "favicon.ico"
github                 = "//github.com/fardog"
highlightjs            = false
lang                   = "en"
noshowreadtime         = false
twitter                = "//twitter.com/milkandtang"
mastodon               = "//mastodon.social/@fardog"

avatar                 = "img/profile.jpg"
privacy_link           = "/privacy/"

[markup]
  [markup.highlight]
  style = "monokailight"
