baseURL = "https://fardog.io/"
languageCode = "en-us"
title = "fardog.io"
theme = "cocoa"

[[menu.main]]
name                   = "Projects"
weight                 = -110
identifier             = "projects"
url                    = "/projects/"

[[menu.main]]
name                   = "Blog"
weight                 = -100
identifier             = "blog"
url                    = "/blog/"

[permalinks]
blog = "blog/:year/:month/:day/:title/"

[params]
latestpostscount       = 5                             # how many posts to display on the home page
i18n_flags             = false                         # whether to display small country flags for available translations
author                 = "Nathan Wittstock"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "web engineer"
# email                  = "nate@fardog.io"
# extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
faviconfile            = "img/leaf.ico"
github                 = "//github.com/fardog"
highlightjs            = true
lang                   = "en"
linkedin               = "//linkedin.com/in/nathan-wittstock-458251a/"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
selfintro              = ""
twitter                = "//twitter.com/milkandtang"
mastodon               = "//mastodon.social/@fardog"

avatar                 = "img/profile.jpg"
